[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[invariant]
call_override = false
fail_on_revert = true
runs = 1000
depth = 20

[profile.ci.invariant]
shrink_run_limit = 0 # takes too damn long to shrink, don't waste Github minutes



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
